#ifndef MONGODBWRAPPER_GLOBAL_H
#define MONGODBWRAPPER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MONGODBWRAPPER_LIB
# define MONGODBWRAPPER_EXPORT Q_DECL_EXPORT
#else
# define MONGODBWRAPPER_EXPORT Q_DECL_IMPORT
#endif

#endif // MONGODBWRAPPER_GLOBAL_H
