#ifndef MYSQLDBWRAPPER_GLOBAL_H
#define MYSQLDBWRAPPER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MYSQLDBWRAPPER_LIB
# define MYSQLDBWRAPPER_EXPORT Q_DECL_EXPORT
#else
# define MYSQLDBWRAPPER_EXPORT Q_DECL_IMPORT
#endif

#endif // MYSQLDBWRAPPER_GLOBAL_H
